[package]
name = "vofa-next-automotive"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
automotive_can = { workspace = true }
automotive_diag = { workspace = true }
automotive_isotp = { workspace = true }
vofa-next-transport = { workspace = true }
libautomotive = { workspace = true }