[package]
name = "vofa-next-core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
vofa_core = { workspace = true }
can_types = { workspace = true }
logic_types = { workspace = true }
diagnostic = { workspace = true }
schema_types = { workspace = true }
