[package]
name = "automotive_isotp"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
vofa-next-core = { workspace = true }
vofa-next-transport = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
async-trait = "0.1"